### ISSUE TITLE
Uncaught exception thread "main" (MC 1.20.1 Fabric Loader 0.16.9)

### ISSUE THREAD

**Issue by Knito58** [chililisoup/BigSignWriter#3]
The game does not start. This is the content of the "pre-launch-window" after installing the mod.

Other mods: modpack EinsZwanzigEins version 1.0.29

```
Uncaught exception in thread "main"
java.lang.RuntimeException: Error parsing or using Mixin config bigsignwriter.mixins.json for mod bigsignwriter
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config bigsignwriter.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:168)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:108)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.7.1 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1822)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:606)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:551)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:479)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1398)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163)
	... 7 more

```
Sorry, no other log file found in logs or crash-reports. These lines are taken from the loader crash window by hitting "Copy error".

**Comment by chililisoup** [comment]
Fixed in 48959ed

**Comment by Knito58** [comment]
Single Player just works. Yay!

I copied the mod file and the 2 config files to the server.

![image](https://github.com/user-attachments/assets/fec61367-efe5-4d81-8667-354b35012034)

What did I forget? The signs should read "DIAMOND FARM".

**Comment by Knito58** [comment]
... And now the same happens on single player, too. How did I possibly kill a working system?

**Comment by Knito58** [comment]
Never mind. As I supposed, it was me the killer. It works on client and server.
![image](https://github.com/user-attachments/assets/ddbc937c-6c89-4c01-942f-4a0586cbcc7c)
My caring Notepad++ corrected the charset settings for me when I looked into the config file. After that, it was corrupted with ?? ? ?.

**Comment by chililisoup** [comment]
Yeah if the config breaks you can delete it and it will regenerate. Also the mod does nothing if it's on the server, it's 100% client-side.
